#!/bin/bash

cat <<eos >info/index.html
<!DOCTYPE html>
<html lang='en'>
    <head>
        <title>kbd.fi</title>
        <style>html,body{font:12pt sans-serif;background-color:#181818;color:#d8d8d8}a{color:#7cafc2}a:visited{color:#ba8baf}</style>
        <meta charset='utf8'>
    </head>
    <body>
        <h1>kbd.fi</h1>
        <p>This is an ever-evolving shortlink service for <a href='http://keyboardfire.com/'>keyboardfire.com</a>. Currently it only does redirects.</p>
        <p>The <code>&lt;a@kbd.fi&gt;</code> email address also lives here, which just forwards to my main email address.</p>
        <h2>List of redirects</h2>
        <ul>
eos

find * -maxdepth 0 -name info -prune -o -type d -print | sort |
while read f
do
    target="$(grep script "$f"/index.html | grep -o "'.*'")"
    echo "<li><a href='http://kbd.fi/$f'>/$f</a>+→ <a href=$target>$(cut -c 25- <<<"$target" | sed s/..\$//)</a>"
done | column -ts+ >> info/index.html

cat <<eos >>info/index.html
        </ul>
    </body>
</html>
eos
